### ISSUE TITLE
Published link does not work

### ISSUE THREAD

**Issue by farling42** [ZWinther/aime-module#2]
Attempting to perform an update from Foundry module settings, tries to use
```
https://raw.githubusercontent.com/ZWinther/aime-module/releases/latest/download/module.json
```
Manually using the following works (github.com), so the module admin packages on foundryvtt.com needs modifying.
```
https://github.com/ZWinther/aime-module/releases/latest/download/module.json
```

**Comment by ZWinther** [comment]
Woops. Should be fixed now.
