### ISSUE TITLE
Standard of Living and Version number

### ISSUE THREAD

**Issue by Mostlylost** [ZWinther/aime-module#4]
First thank you for the module. I have 2 issues. First, the standard of living stat does not seem to save. Plus the updater in FoundryVTT does not see the new update that is available.

Thanks again. Have a great day.

**Comment by ZWinther** [comment]
Hey there, I haven't released a new update yet as the dnd update broke a number of things under the hood, and fixing it was more difficult than I'd expected. 

I hope to release a working version before the weekend.

**Comment by Mostlylost** [comment]
Sorry...I saw that the shadow labels had been fixed. Looking forward for the release.
