### ISSUE TITLE
DND5E 2.2.1 is available on Foundry 10

### ISSUE THREAD

**Issue by farling42** [ZWinther/aime-module#7]
Thanks for the update to work with dnd5e version 2.2.1

However you marked the module as only compatible with Foundry 11, whereas dnd5e version 2.2.1 is also available on Foundry 10.

**Comment by ZWinther** [comment]
Ah I see, that's my bad. I'll fix it after work today.

**Comment by ZWinther** [comment]
Should be available for v10 now.
