### ISSUE TITLE
AiME not working with DND 4.0.0 system

### ISSUE THREAD

**Issue by Old-Skuul** [ZWinther/aime-module#8]
Hello Dan, thank you for all of your work on this module.  I use and love it for my live group.  It was working fine on Foundry V12 and DND 3.3.1 I believe it was.  I turned off all modules after upgrading to DND 4.0.0 and turned only the AiME module back on and it seemed to create some issues.  Especially on NPC actor sheets.  I could not roll the weapons, the tool tips did not show up when i hover on them.  Please take a look when you have time.  Thank you sir

**Comment by ZWinther** [comment]
Sorry, I haven't had time to look at how AiME interacts with the major changes in 4.0.0, so I can't say how much is downright broken or how easy it is to fix.

Unfortunately I'm already swamped with other work at the moment, so I can't say when I'll get to patching this module.

For now, I'd run a separate version of Foundry with the last compatible version of 5e and the backup that was made automatically when you opened the world after the 4.0.0 update.

**Comment by Old-Skuul** [comment]
Hi Dan, yes I did downgrade so I’m back in business.  No worries, thank you for your work on this.
Joe

On Sep 15, 2024, at 10:49 AM, Dan Winther ***@***.***> wrote:

﻿

Sorry, I haven't had time to look at how AiME interacts with the major changes in 4.0.0, so I can't say how much is downright broken or how easy it is to fix.

Unfortunately I'm already swamped with other work at the moment, so I can't say when I'll get to patching this module.

For now, I'd run a separate version of Foundry with the last compatible version of 5e and the backup that was made automatically when you opened the world after the 4.0.0 update.

**Comment by Brittonlj** [comment]
I'd likw ro add another voice to this request.  The issue I'm having is I can't click Complete after I level up a character past level 1.
